CREATE TABLE filmes (
id SERIAL PRIMARY KEY,
titulo VARCHAR(150) NOT NULL,
genero VARCHAR(50),
ano_lancamento INTEGER,
diretor VARCHAR(100)
);
CREATE TABLE usuario (
id SERIAL PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
senha VARCHAR(255) NOT NULL,
ativo BOOLEAN DEFAULT TRUE,
criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);